### ISSUE TITLE
Fragile way of finding the root directory when instantiating QuestionLoader classes

### ISSUE THREAD

**Issue by LoryPack** [LoryPack/LLM-LieDetector#2]
The `QuestionLoader` class's `path_prefix` method goes up in the folder hierarchy until it finds a folder named `["lie_detection", "LLM_lie_detection", "LLM-LieDetector"]`. That however breaks if the user changes the name of the root folder. 

Need to improve this to be more robust. As a minimum, it should return an error if the loop continues for too long.

**Comment by XanderJC** [comment]
Fixed
